# ============================================================
# BACKEND DEPLOYMENT + SERVICE
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gympal-api
spec:
  replicas: 1
  selector:
    matchLabels: # Determine which label (key-value) defines the pods that are part of the pool from this Deployment
      app: gympal-api
  template:
    metadata:
      labels: # Pod's label
        app: gympal-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret # Secret that contains github token for authentication
      containers:
        - name: gympal-api
          image: ghcr.io/smyha/gympal-backend:latest
          ports:
            - containerPort: 3000
          resources: # Resource requests and limits for the container within a Pod
            requests: # Minimum resources required
              cpu: "100m" # millicores
              memory: "128Mi" # mebibytes
            limits: # Maximum resources allowed
              cpu: "500m"
              memory: "256Mi"
          # Environment variables for the container whithin a Pod
          # Load all safe vars
          envFrom: # Load all vars from a ConfigMap
            - configMapRef:
                name: gympal-config
          # Add secret vars explicitly
          env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gympal-secrets
                  key: SUPABASE_URL
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: gympal-secrets
                  key: SUPABASE_ANON_KEY
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: gympal-secrets
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gympal-secrets
                  key: JWT_SECRET
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: gympal-secrets
                  key: SMTP_PASS
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/gympal_dev"
          # Probes to check container health
          readinessProbe: # Check if the container is ready to serve traffic
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe: # Check if the container is alive
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: gympal-api
spec:
  selector: # Select pods with label "app: gympal-api"
    app: gympal-api
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP # Internal service only accessible within the cluster
