# ============================================================
# INGRESS â€” Routes Frontend and Backend
# ============================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gympal-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: gympal.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gympal-api
                port:
                  number: 3000
          # Health check
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: gympal-api
                port:
                  number: 3000

          # Documentation
          - path: /reference
            pathType: Prefix
            backend:
              service:
                name: gympal-api
                port:
                  number: 3000

          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: gympal-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gympal-frontend
                port:
                  number: 80