{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gympal-backend.fullname" . }}-env-secret
  labels:
    {{- include "gympal-backend.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}