apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gympal-frontend.fullname" . }}-env-configmap
  labels:
    {{- include "gympal-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envConfigMap }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
