# ============================================================
# FRONTEND DEPLOYMENT + SERVICE
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gympal-frontend
spec:
  replicas: 1
  selector:
    matchLabels: # Determine which label defines the pods that are part of the pool from this Deployment
      app: gympal-frontend
  template:
    metadata:
      labels:
        app: gympal-frontend
    spec:
      imagePullSecrets: # Secret that contains github token for authentication
        - name: ghcr-secret
      containers:
        - name: gympal-frontend
          image: ghcr.io/arnaugg9/gympalfrontend-frontend:latest
          ports:
            - containerPort: 80
          resources: # Resource requests and limits for the container within a Pod
            requests: # Minimum resources required
              cpu: "100m"
              memory: "128Mi"
            limits: # Maximum resources allowed
              cpu: "250m"
              memory: "256Mi"
          # Environment variables for the container whithin a Pod
          # Safe public vars
          envFrom: # Load all vars from a ConfigMap
            - configMapRef:
                name: gympal-config
          # Sensitive public vars
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gympal-frontend-secrets
                  key: VITE_SUPABASE_URL
            - name: VITE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: gympal-frontend-secrets
                  key: VITE_SUPABASE_ANON_KEY
