# ============================================================
# SECRET â€” Sensitive Keys (Frontend)
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: gympal-frontend-secrets
type: Opaque
stringData:
  # Frontend Secrets
  VITE_SUPABASE_URL: "https://rkqwxbynswjpwibflfik.supabase.co"
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcXd4Ynluc3dqcHdpYmZsZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMDkxNzgsImV4cCI6MjA3NjU4NTE3OH0.-gdk8ZdmvfPHCvHgMtjDGBu7LdggakgPuNVckHTdkwo"