{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gympal-frontend.fullname" . }}-env-secret
  labels:
    {{- include "gympal-frontend.labels" . | nindent 4 }} # include the standard labels
type: Opaque
data:
{{- range $key, $value := .Values.envSecrets }} # Iterate over each key-value pair in envSecrets
  {{ $key }}: {{ $value | b64enc | quote }} # Encode the value in base64 and add it to the secret
{{- end }}
{{- end }}